---
- name: WebLogic Installation and Deployment on RHEL
  hosts: n1
  become: yes
  vars:
    domain_path: "/opt/app/weblogic/user_projects/domains/mydomain"
    admin_user: "weblogic"
    admin_pass: "Web@1234"
    war_file_src: "/tmp/LoginWebApp.war"  # Source WAR file (copied via SCP)
    war_file_dest: "/opt/app/LoginWebApp.war"
    app_name: "LoginWebApp"
    admin_url: "t3://172.24.8.188:7001"
    deploy_script: "/opt/app/deploy_app.py"
    nexus_user: "admin"
    nexus_password: "2418"
    war_repo_url: "http://172.24.8.188:8081/repository/files/LoginWebApp.war"
    war_dest: "/tmp/LoginWebApp.war"

  tasks:

    - name: Ensure security directory exists
      file:
        path: /opt/app/weblogic/user_projects/domains/mydomain/servers/AdminServer/security
        state: directory
        owner: app
        group: appgroup
        mode: '0755'

    # Configure WebLogic to Auto-Start Without Credentials
    - name: Create boot.properties for AdminServer
      copy:
        content: |
          username={{ admin_user }}
          password={{ admin_pass }}
        dest: "{{ domain_path }}/servers/AdminServer/security/boot.properties"
        owner: app
        group: appgroup
        mode: '0600'


    - name: Modify startWebLogic.sh to Auto-Use boot.properties
      lineinfile:
        path: "{{ domain_path }}/bin/startWebLogic.sh"
        insertafter: "DOMAIN_HOME="
        line: "export WLS_USER={{ admin_user }} && export WLS_PW={{ admin_pass }}"

    - name: Start WebLogic Server in Background
      shell: "nohup {{ domain_path }}/bin/startWebLogic.sh &"
      become_user: app
      async: 45
      poll: 0

    # Download LoginWebApp WAR file from Nexus repository
    - name: Download LoginWebApp WAR file from Nexus
      ansible.builtin.uri:
        url: "{{ war_repo_url }}"
        user: "{{ nexus_user }}"
        password: "{{ nexus_password }}"
        method: GET
        force_basic_auth: yes
        dest: "{{ war_dest }}"
      register: download_war
      failed_when: download_war.status not in [200]

    # Ensure correct ownership of WAR file before moving
    - name: Change ownership of WAR file to app:appgroup
      file:
        path: "{{ war_file_src }}"
        owner: app
        group: appgroup
        mode: '0644'

    # Move WAR File to WebLogic Server
    - name: Move WAR file to WebLogic Server
      command: mv {{ war_file_src }} {{ war_file_dest }}
      args:
        removes: "{{ war_file_src }}"  # Removes the WAR file from the source after moving
      become: yes
      become_user: app
      ignore_errors: yes


    - name: Create deploy_app.py script for deployment
      copy:
        content: |
          connect('{{ admin_user }}', '{{ admin_pass }}', '{{ admin_url }}')
          deploy('{{ app_name }}', '{{ war_file_dest }}', targets='AdminServer')
          disconnect()
          exit()
        dest: "{{ deploy_script }}"
        owner: app
        group: appgroup
        mode: '0755'

    - name: Deploy Application via WLST
      shell: |
        cd /opt/app/weblogic/oracle_common/common/bin
        ./wlst.sh {{ deploy_script }}
      become_user: app
      register: deploy_output
      ignore_errors: yes

    - name: Show Deployment Output
      debug:
        msg: "{{ deploy_output.stdout }}"
