---
- name: Install and Configure MySQL 8.4 on RHEL 9 and Migrate from Solaris 11 MySQL 5.7
  hosts: n2
  become: yes
  vars:
    nexus_repo_url: "http://172.24.8.188:8081/repository/files/mysql84-community-release-el9-1.noarch.rpm"
    nexus_user: "admin"
    nexus_password: "2418"
  tasks:

    # Download MySQL 8.4 RPM from Nexus repository
    - name: Download MySQL 8.4 repository file from Nexus
      ansible.builtin.uri:
        url: "{{ nexus_repo_url }}"
        user: "{{ nexus_user }}"
        password: "{{ nexus_password }}"
        method: GET
        force_basic_auth: yes
        dest: /tmp/mysql84-community-release-el9-1.noarch.rpm
      register: download_rpm
      failed_when: download_rpm.status not in [200]

    # Install MySQL 8 repository on RHEL 9
    - name: Install MySQL 8.4 repository from local file
      ansible.builtin.dnf:
        name: /tmp/mysql84-community-release-el9-1.noarch.rpm
        state: present
        disable_gpg_check: yes

    # Install MySQL 8.4
    - name: Install MySQL 8.4
      ansible.builtin.dnf:
        name: mysql-community-server
        state: present

    # Initialize MySQL data directory
    - name: Reinitialize MySQL and generate a new temporary password
      ansible.builtin.shell: |
        rm -rf /var/lib/mysql/*
        mysqld --initialize --user=mysql
      args:
        creates: /var/lib/mysql/mysql
      register: mysql_init
      changed_when: true

    # Start MySQL service on RHEL 9
    - name: Start and enable MySQL service
      ansible.builtin.systemd:
        name: mysqld
        state: started
        enabled: yes

    # Get MySQL root password from the MySQL log
    - name: Get MySQL temporary root password
      shell: "grep -i 'temporary password' /var/log/mysqld.log | tail -n 1 | awk '{print $NF}'"
      register: mysql_root_password
      changed_when: false
      ignore_errors: yes

     # Reset MySQL root password using the temporary password
    - name: Reset MySQL root password
      ansible.builtin.shell: >
        mysql --connect-expired-password -u root -p'{{ mysql_root_password.stdout }}'
        -e "ALTER USER 'root'@'localhost' IDENTIFIED BY 'Matilda@1234';"
      changed_when: true

    # Ensure MySQL is running after password reset
    - name: Restart MySQL service
      ansible.builtin.systemd:
        name: mysqld
        state: restarted
