- name: Create service accounts on RHEL 9
  hosts: n4
  become: yes
  tasks:
    - name: Create service groups
      group:
        name: "{{ item.group }}"
        gid: "{{ item.gid }}"
        state: present
      loop:
        - { group: 'appgroup', gid: '2001' }
        - { group: 'webgroup', gid: '2002' }
        - { group: 'dbgroup', gid: '2003' }

    - name: Create service accounts
      user:
        name: "{{ item.user }}"
        uid: "{{ item.uid }}"
        group: "{{ item.group }}"
        shell: /bin/bash
        home: "{{ item.home }}"
        create_home: yes
        state: present
      loop:
        - { user: 'app', uid: '1001', group: 'appgroup', home: '/opt/app' }
        - { user: 'web', uid: '1002', group: 'webgroup', home: '/opt/web' }
        - { user: 'db', uid: '1003', group: 'dbgroup', home: '/opt/db' }

    - name: Set permissions for home directories
      file:
        path: "{{ item.home }}"
        owner: "{{ item.user }}"
        group: "{{ item.group }}"
        mode: '0750'
        state: directory
      loop:
        - { user: 'app', group: 'appgroup', home: '/opt/app' }
        - { user: 'web', group: 'webgroup', home: '/opt/web' }
        - { user: 'db', group: 'dbgroup', home: '/opt/db' }
 