---
- name: WebLogic Installation on RHEL
  hosts: n1
  become: yes
  vars:
    jar_src: "/tmp/weblogic.jar"  # Location where JAR file is copied via SCP
    jar_dest: "/opt/app/weblogic.jar"  # Destination path

  tasks:

    # Create app group
    - name: Create app group
      group:
        name: appgroup
        state: present

    # Create app user
    - name: Create app user
      user:
        name: app
        group: appgroup
        create_home: yes
        shell: /bin/bash
        state: present

    # Create /opt/app directory if not exists
    - name: Create /opt/app directory
      file:
        path: /opt/app
        state: directory
        owner: app
        group: appgroup
        mode: '0755'

    # Move WebLogic JAR file from /tmp to /opt/app/
    - name: Move WebLogic JAR file to /opt/app
      command: mv {{ jar_src }} {{ jar_dest }}
      args:
        removes: "{{ jar_src }}"  # Removes JAR from /tmp after moving
      become: yes  # Run as root to move file
      ignore_errors: no

    # Set correct ownership and permissions for WebLogic JAR
    - name: Set ownership and permissions for WebLogic JAR
      file:
        path: "{{ jar_dest }}"
        owner: app
        group: appgroup
        mode: '0755'

    # Install Java 8 if not installed
    - name: Check if Java 8 is installed
      command: java -version
      register: java_check
      ignore_errors: yes
      changed_when: false

    - name: Install Java 8 (if not present)
      yum:
        name: java-1.8.0-openjdk
        state: present
      when: java_check.failed

    # Create WebLogic response file (response.rsp)
    - name: Create response.rsp file
      copy:
        content: |
          [ENGINE]
          Response File Version=1.0.0.0.0
          
          [GENERIC]
          ORACLE_HOME=/opt/app/weblogic
          INSTALL_TYPE=WebLogic Server
        dest: /opt/app/response.rsp
        owner: app
        group: appgroup
        mode: '0644'

    # Create central inventory location file (oraInst.loc)
    - name: Create oraInst.loc file
      copy:
        content: |
          inst_group=appgroup
          inventory_loc=/opt/weblogicapp/oraInventory
        dest: /var/opt/oracle/oraInst.loc
        owner: root
        group: root
        mode: '0644'

    # Run WebLogic installer
    - name: Run WebLogic installer
      command: java -jar {{ jar_dest }} -silent -responseFile /opt/app/response.rsp -invPtrLoc /var/opt/oracle/oraInst.loc
      become_user: app
      register: weblogic_install
      ignore_errors: yes

    # Configure WebLogic domain using WLST
    - name: Create WebLogic domain
      command: "/opt/app/weblogic/oracle_common/common/bin/wlst.sh /opt/app/create_domain.py"
      become_user: app
      register: create_domain
      ignore_errors: yes

    # Start WebLogic server
    - name: Start WebLogic server
      command: "/opt/app/weblogic/user_projects/domains/mydomain/bin/startWebLogic.sh"
      become_user: app
      register: start_weblogic
      ignore_errors: yes

    # Show outputs
    - name: Show WebLogic installation output
      debug:
        msg: "{{ weblogic_install.stdout }}"

    - name: Show domain creation output
      debug:
        msg: "{{ create_domain.stdout }}"

    - name: Show WebLogic start output
      debug:
        msg: "{{ start_weblogic.stdout }}"
